In [28]:
### CREATING A CLASS FOR STORING DATA FOR EACH NODE ###

class tree():
            
    def __init__(self, branch_len=None, seq_leaf=None, node_name=None, parent=None, child=None, nuc_list=None, lkl_list=None, type=None):
        self.seq_leaf = seq_leaf
        self.child = child ## this is the same as node name
        self.parent = parent
        self.branch_length = branch_len
        self.nuc_list = nuc_list
        self.lkl_list = lkl_list
        self.name = node_name
        self.type = type ## is it the external node or internal node

    def __len__(self):
        return len(self.seq_leaf)
    
    def getSequence(self):
        return self.seq_leaf
    
    def getBranchLength(self):
        return self.branch_length
       
    def getChildrenNodes(self):
        return self.child
    
    def get_nuc_list(self):
        return self.nuc_list
    
    def get_lkl_list(self):
        return self.lkl_list
    
    def initialize_nuc_list(self):
        if self.seq_leaf:
            bases={"A":[1,0,0,0],
                "C":[0,1,0,0],
                "G":[0,0,1,0],
                "T":[0,0,0,1]}
            self.nuc_list=list()
            for base in self.seq_leaf:
                self.nuc_list.append(bases[base])
            return self.nuc_list
        else: return None

In [29]:
### reading data and adding nodes as objects ###

branch_lengths_path="data/branchlength.dat"
tree_path="data/table.dat"
msa_path="data/msa.dat"


### Reading tree topology, branch lengths and seqeunces ###
with open(tree_path,"r") as tree_file, open(branch_lengths_path,"r") as BL_file, open(msa_path,"r") as msa_file:
    node_added_tmp=[] #list with nodes added to tree to update children
    Tree_Data=[]
    line_num=0
    
    bl=BL_file.readline().split(",")
    seq_for_leaves = {}
    for line in msa_file:
       (key, val) = line.split()
       seq_for_leaves[int(key)] = val


    for parent_child in tree_file:
        tmp_list=parent_child.split(",")

        parent_node_name=tmp_list[0]
        child_node_name=tmp_list[1].rstrip()

        branch_len=bl[line_num]

        if int(child_node_name) in seq_for_leaves.keys():
            leaf_seq=seq_for_leaves[int(child_node_name)]
            type="external" ## can be removed
        else:
            leaf_seq=None
            type="internal" # can be removed
        
        new_node = tree(branch_len=branch_len,
            seq_leaf=leaf_seq,
            type=type,
            node_name=child_node_name,
            parent=parent_node_name,
            child=child_node_name,
            nuc_list=[],
            lkl_list=[])
        new_node.initialize_nuc_list()
        
        Tree_Data.append(new_node)
        line_num+=1

In [30]:
## checking if data loaded correctly
for obj in Tree_Data:
    print("node type    : " , obj.type)
    print("Parent name  : ",obj.parent)
    print("current name : ",obj.name)
    print("Child name   : ",obj.child) ## same as node name
    print("Branch length: ",obj.branch_length)
    print("sequence     : ", obj.seq_leaf)
    print("nuc_list updated: " , obj.get_nuc_list())
    print("lkl_list updated: " , obj.get_lkl_list())


node type    :  external
Parent name  :  9
current name :  1
Child name   :  1
Branch length:  0.1
sequence     :  AGATCAAGATCAAGATCAAGATCAAGATCA
nuc_list updated:  [[1, 0, 0, 0], [0, 0, 1, 0], [1, 0, 0, 0], [0, 0, 0, 1], [0, 1, 0, 0], [1, 0, 0, 0], [1, 0, 0, 0], [0, 0, 1, 0], [1, 0, 0, 0], [0, 0, 0, 1], [0, 1, 0, 0], [1, 0, 0, 0], [1, 0, 0, 0], [0, 0, 1, 0], [1, 0, 0, 0], [0, 0, 0, 1], [0, 1, 0, 0], [1, 0, 0, 0], [1, 0, 0, 0], [0, 0, 1, 0], [1, 0, 0, 0], [0, 0, 0, 1], [0, 1, 0, 0], [1, 0, 0, 0], [1, 0, 0, 0], [0, 0, 1, 0], [1, 0, 0, 0], [0, 0, 0, 1], [0, 1, 0, 0], [1, 0, 0, 0]]
lkl_list updated:  []
node type    :  external
Parent name  :  9
current name :  2
Child name   :  2
Branch length:  0.4
sequence     :  AGCTCAAGCTCAAGCTCAAGCTCAAGCTCA
nuc_list updated:  [[1, 0, 0, 0], [0, 0, 1, 0], [0, 1, 0, 0], [0, 0, 0, 1], [0, 1, 0, 0], [1, 0, 0, 0], [1, 0, 0, 0], [0, 0, 1, 0], [0, 1, 0, 0], [0, 0, 0, 1], [0, 1, 0, 0], [1, 0, 0, 0], [1, 0, 0, 0], [0, 0, 1, 0], [0, 1, 0, 0], [0, 0, 0, 1], [0

In [31]:
import numpy as np
import scipy
from scipy.linalg import expm, sinm, cosm
mu=1 # USER INPUT
Q=np.array([[-3*mu, mu, mu, mu], [mu, -3*mu,  mu, mu], [ mu, mu, -3*mu, mu], [ mu, mu, mu, -3*mu]]) #symbolic of the model of evolution


## dict to store liklihoods of nucleotides at each site s in all nodes
lkl_dict = {}


## updating lkl lists for external nodes
for node in Tree_Data:
    if node.getSequence() is not None: # if it is not internal node 
        nuc_list=node.get_nuc_list() # which nuc is present at each pposition --> a list of lists like [[1,0,0,0],[0,1,0,0]....]
        Probability_Matrix = scipy.linalg.expm(Q * float(node.getBranchLength())) # same for all positions
        for pos_list in nuc_list:
            node.lkl_list.append(np.matmul(Probability_Matrix,pos_list))
        lkl_dict[node.name]=node.lkl_list


#!! checkpoint
#for node in lkl_dict:
#    print("dict", node ," ",lkl_dict[node])


dict 1   [array([0.75274003, 0.08241999, 0.08241999, 0.08241999]), array([0.08241999, 0.08241999, 0.75274003, 0.08241999]), array([0.75274003, 0.08241999, 0.08241999, 0.08241999]), array([0.08241999, 0.08241999, 0.08241999, 0.75274003]), array([0.08241999, 0.75274003, 0.08241999, 0.08241999]), array([0.75274003, 0.08241999, 0.08241999, 0.08241999]), array([0.75274003, 0.08241999, 0.08241999, 0.08241999]), array([0.08241999, 0.08241999, 0.75274003, 0.08241999]), array([0.75274003, 0.08241999, 0.08241999, 0.08241999]), array([0.08241999, 0.08241999, 0.08241999, 0.75274003]), array([0.08241999, 0.75274003, 0.08241999, 0.08241999]), array([0.75274003, 0.08241999, 0.08241999, 0.08241999]), array([0.75274003, 0.08241999, 0.08241999, 0.08241999]), array([0.08241999, 0.08241999, 0.75274003, 0.08241999]), array([0.75274003, 0.08241999, 0.08241999, 0.08241999]), array([0.08241999, 0.08241999, 0.08241999, 0.75274003]), array([0.08241999, 0.75274003, 0.08241999, 0.08241999]), array([0.75274003, 0.

In [72]:
### MAIN CALCULATION ###

## keeping track of parents nodes that ahve been calculated
parent_nodes_visited=[]

for nodeA in Tree_Data:
    for nodeB in Tree_Data:
        if nodeA != nodeB: ## if not the same node
            # get two siblings from the tree i.e nodes having same parent
            if nodeA.parent == nodeB.parent and not (nodeA.parent in parent_nodes_visited):

                childA_lkl = lkl_dict[nodeA.name] # we will get a list of lists with liklihood for each nuclleotide at each position
                childB_lkl = lkl_dict[nodeB.name]
                anc_AB_lkl=[]
                anc_name=nodeA.parent #could likewise be nodeB.parent

                # calculating the liklihood of all 4 nucleotides at each position for the parent
                for pos_list in range(len(childA_lkl)): #using all positions in both children nodes, calculate ancetral nucleotide liklihoods 
                    vec1=childA_lkl[pos_list]
                    vec2=childB_lkl[pos_list]
                    vec_anc = [vec1[i] * vec2[i] for i in range(4)]
                    vec_anc = np.multiply(vec_anc, 0.25) # probbaility of observing each nucleotide in nature
                    #vec_anc=np.log(vec_anc)

                    ## !! CHECKPOINT !! ##
                    print("node",nodeA.parent,vec_anc) ## we are geiting 4 values/pos i.e lkl of all 4 nucleotides at each position.

                    anc_AB_lkl.append(np.array(vec_anc)) ## position lkl to main list for this node

                lkl_dict[anc_name]=anc_AB_lkl # updating lkl_dict
                parent_nodes_visited.append(nodeA.parent) # mark parent as vivited

node 9 [0.07554168 0.00411123 0.00411123 0.00411123]
node 9 [0.00411123 0.00411123 0.07554168 0.00411123]
node 9 [0.03754778 0.00827131 0.00411123 0.00411123]
node 9 [0.00411123 0.00411123 0.00411123 0.07554168]
node 9 [0.00411123 0.07554168 0.00411123 0.00411123]
node 9 [0.07554168 0.00411123 0.00411123 0.00411123]
node 9 [0.07554168 0.00411123 0.00411123 0.00411123]
node 9 [0.00411123 0.00411123 0.07554168 0.00411123]
node 9 [0.03754778 0.00827131 0.00411123 0.00411123]
node 9 [0.00411123 0.00411123 0.00411123 0.07554168]
node 9 [0.00411123 0.07554168 0.00411123 0.00411123]
node 9 [0.07554168 0.00411123 0.00411123 0.00411123]
node 9 [0.07554168 0.00411123 0.00411123 0.00411123]
node 9 [0.00411123 0.00411123 0.07554168 0.00411123]
node 9 [0.03754778 0.00827131 0.00411123 0.00411123]
node 9 [0.00411123 0.00411123 0.00411123 0.07554168]
node 9 [0.00411123 0.07554168 0.00411123 0.00411123]
node 9 [0.07554168 0.00411123 0.00411123 0.00411123]
node 9 [0.07554168 0.00411123 0.00411123 0.004

In [52]:
np.log(np.matmul(vec_anc, [0.25,0.25,0.25,0.25]))

-14.469698794098445

In [59]:
lkl_dict


{'1': [array([0.75274003, 0.08241999, 0.08241999, 0.08241999]),
  array([0.08241999, 0.08241999, 0.75274003, 0.08241999]),
  array([0.75274003, 0.08241999, 0.08241999, 0.08241999]),
  array([0.08241999, 0.08241999, 0.08241999, 0.75274003]),
  array([0.08241999, 0.75274003, 0.08241999, 0.08241999]),
  array([0.75274003, 0.08241999, 0.08241999, 0.08241999]),
  array([0.75274003, 0.08241999, 0.08241999, 0.08241999]),
  array([0.08241999, 0.08241999, 0.75274003, 0.08241999]),
  array([0.75274003, 0.08241999, 0.08241999, 0.08241999]),
  array([0.08241999, 0.08241999, 0.08241999, 0.75274003]),
  array([0.08241999, 0.75274003, 0.08241999, 0.08241999]),
  array([0.75274003, 0.08241999, 0.08241999, 0.08241999]),
  array([0.75274003, 0.08241999, 0.08241999, 0.08241999]),
  array([0.08241999, 0.08241999, 0.75274003, 0.08241999]),
  array([0.75274003, 0.08241999, 0.08241999, 0.08241999]),
  array([0.08241999, 0.08241999, 0.08241999, 0.75274003]),
  array([0.08241999, 0.75274003, 0.08241999, 0.0824

In [84]:
for node in lkl_dict:
    node_lkl=0
    for pos_list in lkl_dict[node]:
        pos_list=np.log(pos_list)
        node_lkl+=sum(pos_list)
    print("Node ",node,"liklihood: ",node_lkl,2**(node_lkl))
    

Node  1 liklihood:  -233.15451685769935 6.508738169392566e-71
Node  2 liklihood:  -172.44525573704078 1.2268893969390092e-52
Node  3 liklihood:  -300.32894703127226 3.908214371458486e-91
Node  4 liklihood:  -194.44416487709873 2.9273448737329587e-59
Node  5 liklihood:  -248.22895353828332 1.8864234770462425e-75
Node  9 liklihood:  -571.9550959291269 6.673596618768205e-173
Node  8 liklihood:  -1038.6393662947862 2.1796967058e-313
Node  7 liklihood:  -609.0284417497687 4.6149906005491674e-184
Node  6 liklihood:  -1814.023131378942 0.0


Ignore the code below!!

In [49]:
#for obj_with_seq in objects_with_sequence:
for obj_with_seq in nodes_with_sequence:
    # Perform operations or access attributes for objects without sequences
    print(f"Object without sequence: {obj_with_seq.name, obj_with_seq.parent, obj_with_seq.child}")


lkl_dict.keys()

Object without sequence: ('1', '9', '1')
Object without sequence: ('2', '9', '2')
Object without sequence: ('3', '8', '3')
Object without sequence: ('4', '7', '4')
Object without sequence: ('5', '7', '5')


dict_keys(['1', '2', '3', '4', '5', '9', '8', '7', '6'])

In [52]:
children = dict()
for node in Tree_Data:
    if node.parent not in children:
        children[node.parent] = [node.child]
    else:
        children[node.parent].append(node.child)

print(children)
for parent, childs in children.items():
    print(childs)

{'9': ['1', '2'], '8': ['9', '3'], '7': ['4', '5'], '6': ['7', '8']}
['1', '2']
['9', '3']
['4', '5']
['7', '8']


In [ ]:
# Separating external and internal nodes
external_nodes = []
internal_nodes = []

for node in Tree_Data:
    if node.getSequence() is not None:
        external_nodes.append(node)
    else:
        internal_nodes.append(node)

# Loop through objects with sequences
for node in external_nodes:
    # Perform operations or access attributes for objects with sequences
    print(f"Object with sequence: {node.name}")
    

# Loop through objects without sequences
for node in internal_nodes:
    # Perform operations or access attributes for objects without sequences
    print(f"Object without sequence: {node.name}")